### ISSUE TITLE
Drag drop between layers

### ISSUE THREAD

**Issue by IanMayo** [debrief/limpet#125]
We have hierarchical layers (#41).

We need to implement drag/drop between the layers/groups.

**Comment by IanMayo** [comment]
@pecko - could you start this one please.

To start with, we can drag any dataset into any folder.

There is a button on the limpet editor toolbar to create a new layer (folder).

**Comment by pecko** [comment]
@IanMayo 

I have prepared this feature, but have 3 questions:

1) There is already drop for csv files. It is saved directly to model root. We can save it to folder(layer) if user drop the file to a layer
For now, I keep it as is.

2) We can drag&drop some *.lap file to folder layer if user drop it to folder (and/or directly to model root if user drop it somewhere else)

3) I suppose that an element is folder/layer if it is instance of GroupWrapper. Is it correct?

Please let me know what you want me to do. Maybe you want to drag/drop some other input/dataset too.

**Comment by IanMayo** [comment]
Hi there,
the focus of this issue was dragging around (organising) datasets that are already loaded in the editor window.

Back to your answers.

1) - Yes, let's allow a CSV to be dropped into a folder or the root.
2) - No, let's defer dropping *.lap files into an open editor
3) - Yes.

**Comment by pecko** [comment]
I have created the PR: https://github.com/debrief/limpet/pull/159

The following is added:
- a csv file can be dropped to folder
- a folder (GroupWrapper) and collection (CollectionWrapper) can be dropped to folder
- drag and drop works between different editor (you can open another editor in separate window)

I have use existing XStreamHandler to convert an artifact to xml and from xml.

@IanMayo 
Please review and suggest if I would add something else

**Comment by IanMayo** [comment]
Hmm, I've checked out Issue125.  But, when I've got the editor open, with some datasets loaded, I can't drag any of them.

When I drag a CSV file, and drop it onto a "Folder" in the editor, the new CSV appears at the top level.

Is there a chance you haven't pushed some changes?

**Comment by pecko** [comment]
You are right. Sorry. Now, it is pushed.

**Comment by IanMayo** [comment]
Got a problem with dragging datasets. 

Steps to reproduce:
- open the (empty) americas.lap file
- drag in usa.csv - the new folder of data will appear
- right-click on usa-Location, and select _Spatial / Generate calculated course_
- a new dataset appears, at the root level: _Generated course for usa-Location_
- drag this dataset into the usa.csv folder

There are two problems:
- the _Generated course..._ file goes into usa.csv, but it's put into it's own folder in there
- a copy of the dataset stays at the root level

![draggeddataset](https://cloud.githubusercontent.com/assets/1108513/11612553/3d1d7916-9bf7-11e5-809b-b654af8e2108.png)

**Comment by pecko** [comment]
Fixed by the commit: https://github.com/pecko/limpet/commit/78d426ed1100a88d88f124a83419189876d85477

**Comment by IanMayo** [comment]
@pecko  - the second problem isn't fixed.  After dragging a dataset into a folder, a copy of the dataset is still left at the previous location.

It looks like one cause of the problem is that in LimpetTransfer.readWrappers() we pass **null** as the parent parameter to **new CollectionWrapper()**

When I move a dataset from one folder to another (in the same project), we go through this XML transfer.  I'm sure we don't need to do this.  I appreciate it would be necessary for moving between editors, but not in the same editor.  When we do this within the same editor it wrongly creates a duplicate that is no longer "linked" the precedent/dependent items.

Actually, it seems trouble-some to move a dataset between editors, particularly when the dataset has been used in a calculation.  If we perform a calculation using a dataset (such as right-clicking on usa-Wind Direction and selection _Arithmetic / Sin_, then it can no longer be copy/pasted (xstream fails).

So, for now, let's drop drag/drop between editors, and focus on supporting it inside the current editor (without using xstream).

It looks like we need to correctly store/manage the _parent_ attribute for CollectionWrapper.

**Comment by pecko** [comment]
Actualy you want DROP_MOVE, but not DROP_COPY. It depends on OS and usually some key (Shift, Ctrl) determines if you will move or copy. I haven't implemented MOVE. Will fix it.

> When I move a dataset from one folder to another (in the same project), we go through this XML 
> transfer. I'm sure we don't need to do this. I appreciate it would be necessary for moving between 
> editors, but not in the same editor. When we do this within the same editor it wrongly creates a 
> duplicate that is no longer "linked" the precedent/dependent items.

It probably can be implemented differently, but you have to create a serialization to array of byte or something what OS understand. You can't D&D Java object. It has to be converted to OS native object no matter if it is within the same application, widget (editor) or different applications.

I think that we just have to implement DRAG_MOVE correctly and it will not be important if it is between the same editor, different editors or even different Limpet instances. Will try do it  later and let you know.

**Comment by pecko** [comment]
> Actually, it seems trouble-some to move a dataset between editors, particularly when the dataset 
> has been used in a calculation. If we perform a calculation using a dataset (such as right-clicking on 
> usa-Wind Direction and selection Arithmetic / Sin, then it can no longer be copy/pasted (xstream fails).

Will check. Could you let me know exactly steps how to try that?
What when we save such editor? Does the calculation persisted?

> So, for now, let's drop drag/drop between editors, and focus on supporting it inside the current 
> editor (without using xstream).

Other option that I can try is Java serialization, but it would be also create a xml file that have to be convert to byte array. Maybe it wouldn't fails.

> It looks like we need to correctly store/manage the parent attribute for CollectionWrapper

Will fix. I think that it's doable.

**Comment by pecko** [comment]
> It looks like one cause of the problem is that in LimpetTransfer.readWrappers() we pass null as the parent parameter to new CollectionWrapper()

You mean that parent should be the same regardless if we copy/move a collection in another place.

**Comment by IanMayo** [comment]
Ok, have made some PRs that relate to this.

All objects in the data model now have a UUID ( #165  ):
     myId = object.getUUID();

All objects now know about their parent object  ( #164   ).  So, you can call:
     object.getParent().remove(object);

**Comment by IanMayo** [comment]
Hmm, I think I have this working - using UUIDs.

The implementation is in #159, and has been merged.

I'd appreciate you reviewing the implementation, please.

**Comment by pecko** [comment]
There is an issue when opening a lap file. Checking...

**Comment by pecko** [comment]
I have create a new PR: https://github.com/debrief/limpet/pull/166
There are two issues that are explained in the commit message.
